### ISSUE TITLE
you did not pack your finished images

### ISSUE THREAD

**Issue by BluePrintRandom** [alcove-design/blender-world-night-sky#1]
![image](https://github.com/alcove-design/blender-world-night-sky/assets/7190873/2765144d-bdcb-429b-8a88-6a3c096b3726)
tis all pink over here friend.

**Comment by mef** [comment]
Hi, yes, this is on purpose: 

The stars map is available in a variety of resolutions (from 4K - 34 MB to 64k - 3.8GB), so they have not been included in order to keep the file lightweight. 

It is up to the user to download and use the file from NASA website at a resolution fit for his usage scenario. Latest update of the star map at time of writing is in [this page](https://svs.gsfc.nasa.gov/4851/), with NASA now providing the map files in EXR format.

Setup instructions are in the README.md file. 

This said, the approach taken in this blend file is probably not optimal, in terms of performance: it would certainly make more sense to display the stars map as a background to the world, but not light the scene with it.

I am focused on other projects at the moment, so not planning to do any change shortly.
